# Generated by Django 4.1.5 on 2023-02-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candy",
            fields=[
                (
                    "name",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                ("flavor", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=30)),
                ("year_created", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car2",
            fields=[
                (
                    "brand",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("year", models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="car",
            name="id",
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(
                auto_created=True,
                blank=True,
                max_length=250,
                primary_key=True,
                serialize=False,
                verbose_name="name",
            ),
        ),
    ]
